### ISSUE TITLE
nest installation interrupts with ipython

### ISSUE THREAD

**Issue by nosratullah** [conda-forge/nest-simulator-feedstock#22]
Hi,
I installed the below nest version :
nest-2.18.0
macOS Mojave 10.14.6
I can import nest in python itself. but whenever I use ipython I get this error :
![image](https://user-images.githubusercontent.com/13776994/65394307-ed72c500-dd98-11e9-966c-2d40561df0cb.png)
whenever I lunch jupyter notebook or jupyter-lab I get this error :
![image](https://user-images.githubusercontent.com/13776994/65394308-f5cb0000-dd98-11e9-91aa-468f6b50b102.png)

could you please give me a help :)

**Comment by steffengraber** [comment]
Hi @nosratullah 
please follow the manual installation on macOS instructions:
https://nest-simulator.readthedocs.io/en/latest/installation/mac_install.html#manual-installation

**Comment by steffengraber** [comment]
Hi @nosratullah 
in the last days I have taken a closer look at the problem, but could not find a solution so far. 
The NEST developers are aware of the situation. 
There is a new major release of NEST in the pipeline which brings major changes. As long as this is not yet available, I can only recommend the manual installation of NEST in macOS.

**Comment by nosratullah** [comment]
Hello, @steffengraber 
thanks for the time you put on this problem. So far I am using NEST without jupyter, and it's fine. I'm looking forward to seeing the new release.

**Comment by steffengraber** [comment]
I will close the issue until further notice.
