### ISSUE TITLE
Add osx-arm64 builds

### ISSUE THREAD

**Issue by espenhgn** [conda-forge/nest-simulator-feedstock#62]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Builds for M1 macs (platform osx-arm64) are not available. That would be nice.

**Comment by steffengraber** [comment]
@espenhgn Took a long time, but osx-arm64 builds are now available - the issue will be closed. Any feedback on the new packages would be helpful.

**Comment by espenhgn** [comment]
Thanks, seems to work fine on my end.
